stages:
  - test

unit-integration-e2e-test:
  image: node:latest
  stage: test
  tags:
    - coverage
  before_script:
    - yarn install # 安装依赖
    - yarn build # 构建项目
  script:
    - yarn test # 运行测试脚本
  coverage: /Statements\s+:\s+([\d\.]+)%\s+\(\s*\d+\/\d+\s*\)/ # 根据你的覆盖率输出调整正则表达式
  artifacts:
    paths:
      - coverage/ # 保存覆盖率报告
