name: Publish Package to npmjs

on:
  workflow_dispatch: # 手动触发
  push:
    branches:
      - main # 在 main 分支推送时触发
      - dev/**

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 设置 Node.js 环境
      - uses: actions/setup-node@v3
        with:
          node-version: '21.x'
          registry-url: 'https://registry.npmjs.org'

      # 安装依赖
      - run: yarn install

      - run: yarn build

      # 运行测试（可选）
      - run: yarn test:unit

      # 运行 semantic-release 来自动管理版本和发布
      - run: yarn semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # 从 GitHub Secrets 中获取 NPM token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token，用于创建 release 和标签
