name: Test Coverage

env:
  TEST_SCRIPT: ${{vars.TEST_SCRIPT ||  'test:unit'}}

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & Test Lib
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
      - run: yarn config list
      - run: yarn install
      - run: yarn ${{env.TEST_SCRIPT}}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
