name: Test Coverage

env:
  TEST_SCRIPT: ${{vars.TEST_SCRIPT ||  'test:unit'}}

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build & Test Lib
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - run: pnpm ${{env.TEST_SCRIPT}}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
